// This file is auto-generated by @hey-api/openapi-ts

export type CampyearCampyearResponse = {
    active: boolean;
    createdAt: string;
    end: string;
    insuranceFee: number;
    open: boolean;
    participationFee: number;
    start: string;
    updatedAt: string;
    year: number;
};

export type CampyearCreateCampyearRequest = {
    end: string;
    insuranceFee: number;
    participationFee: number;
    start: string;
    year: number;
};

export type CampyearCreateCampyearResponse = {
    campyear: CampyearCampyearResponse;
};

export type CampyearGetCampyearResponse = {
    campyear: CampyearCampyearResponse;
};

export type CampyearListCampyearsResponse = {
    campyears: Array<CampyearCampyearResponse>;
    count: number;
};

export type CampyearUpdateCampyearRequest = {
    end: string;
    insuranceFee: number;
    participationFee: number;
    start: string;
};

export type CampyearUpdateCampyearResponse = {
    campyear: CampyearCampyearResponse;
};

export type PersonRestError = {
    code: string;
    description: string;
    fields?: {
        [key: string]: string;
    };
    message: string;
    meta?: {
        [key: string]: string;
    };
};

export type ListCampyearsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/';
};

export type ListCampyearsErrors = {
    /**
     * Internal server error
     */
    500: PersonRestError;
};

export type ListCampyearsError = ListCampyearsErrors[keyof ListCampyearsErrors];

export type ListCampyearsResponses = {
    /**
     * List of campyears retrieved successfully
     */
    200: CampyearListCampyearsResponse;
};

export type ListCampyearsResponse = ListCampyearsResponses[keyof ListCampyearsResponses];

export type CreateCampyearData = {
    /**
     * Campyear data
     */
    body: CampyearCreateCampyearRequest;
    path?: never;
    query?: never;
    url: '/api/v1/';
};

export type CreateCampyearErrors = {
    /**
     * Bad request - invalid JSON or date format
     */
    400: PersonRestError;
    /**
     * Validation error - invalid field values
     */
    422: PersonRestError;
    /**
     * Internal server error
     */
    500: PersonRestError;
};

export type CreateCampyearError = CreateCampyearErrors[keyof CreateCampyearErrors];

export type CreateCampyearResponses = {
    /**
     * Campyear created successfully
     */
    201: CampyearCreateCampyearResponse;
};

export type CreateCampyearResponse = CreateCampyearResponses[keyof CreateCampyearResponses];

export type GetActiveCampyearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/active';
};

export type GetActiveCampyearErrors = {
    /**
     * Campyear not found
     */
    404: PersonRestError;
};

export type GetActiveCampyearError = GetActiveCampyearErrors[keyof GetActiveCampyearErrors];

export type GetActiveCampyearResponses = {
    /**
     * Active campyear retrieved successfully
     */
    200: CampyearGetCampyearResponse;
};

export type GetActiveCampyearResponse = GetActiveCampyearResponses[keyof GetActiveCampyearResponses];

export type DeleteCampyearData = {
    body?: never;
    path: {
        /**
         * Campyear Year
         */
        year: number;
    };
    query?: never;
    url: '/api/v1/{year}';
};

export type DeleteCampyearErrors = {
    /**
     * Bad request - invalid year format
     */
    400: PersonRestError;
    /**
     * Internal server error
     */
    500: PersonRestError;
};

export type DeleteCampyearError = DeleteCampyearErrors[keyof DeleteCampyearErrors];

export type DeleteCampyearResponses = {
    /**
     * Campyear deleted successfully
     */
    204: unknown;
};

export type GetCampyearData = {
    body?: never;
    path: {
        /**
         * Campyear Year
         */
        year: number;
    };
    query?: never;
    url: '/api/v1/{year}';
};

export type GetCampyearErrors = {
    /**
     * Bad request - invalid year format
     */
    400: PersonRestError;
    /**
     * Campyear not found
     */
    404: PersonRestError;
};

export type GetCampyearError = GetCampyearErrors[keyof GetCampyearErrors];

export type GetCampyearResponses = {
    /**
     * Campyear details retrieved successfully
     */
    200: CampyearGetCampyearResponse;
};

export type GetCampyearResponse = GetCampyearResponses[keyof GetCampyearResponses];

export type UpdateCampyearData = {
    /**
     * Updated campyear data
     */
    body: CampyearUpdateCampyearRequest;
    path: {
        /**
         * Campyear Year
         */
        year: number;
    };
    query?: never;
    url: '/api/v1/{year}';
};

export type UpdateCampyearErrors = {
    /**
     * Bad request - invalid year or date format
     */
    400: PersonRestError;
    /**
     * Validation error - invalid field values
     */
    422: PersonRestError;
    /**
     * Internal server error
     */
    500: PersonRestError;
};

export type UpdateCampyearError = UpdateCampyearErrors[keyof UpdateCampyearErrors];

export type UpdateCampyearResponses = {
    /**
     * Campyear updated successfully
     */
    200: CampyearUpdateCampyearResponse;
};

export type UpdateCampyearResponse = UpdateCampyearResponses[keyof UpdateCampyearResponses];

export type ActivateCampyearData = {
    body?: never;
    path: {
        /**
         * Year of the campyear
         */
        year: number;
    };
    query?: never;
    url: '/api/v1/{year}/activate';
};

export type ActivateCampyearErrors = {
    /**
     * Ongeldig jaarformaat
     */
    400: PersonRestError;
    /**
     * Internal server error
     */
    500: PersonRestError;
};

export type ActivateCampyearError = ActivateCampyearErrors[keyof ActivateCampyearErrors];

export type ActivateCampyearResponses = {
    /**
     * Campyear activated
     */
    200: string;
};

export type ActivateCampyearResponse = ActivateCampyearResponses[keyof ActivateCampyearResponses];

export type CloseCampyearData = {
    body?: never;
    path: {
        /**
         * Year of the campyear
         */
        year: number;
    };
    query?: never;
    url: '/api/v1/{year}/close';
};

export type CloseCampyearErrors = {
    /**
     * Invalid year format
     */
    400: PersonRestError;
    /**
     * Internal server error
     */
    500: PersonRestError;
};

export type CloseCampyearError = CloseCampyearErrors[keyof CloseCampyearErrors];

export type CloseCampyearResponses = {
    /**
     * Campyear closed
     */
    200: string;
};

export type CloseCampyearResponse = CloseCampyearResponses[keyof CloseCampyearResponses];

export type OpenCampyearData = {
    body?: never;
    path: {
        /**
         * Year of the campyear
         */
        year: number;
    };
    query?: never;
    url: '/api/v1/{year}/open';
};

export type OpenCampyearErrors = {
    /**
     * Invalid year format
     */
    400: PersonRestError;
    /**
     * Internal server error
     */
    500: PersonRestError;
};

export type OpenCampyearError = OpenCampyearErrors[keyof OpenCampyearErrors];

export type OpenCampyearResponses = {
    /**
     * Campyear opened
     */
    200: string;
};

export type OpenCampyearResponse = OpenCampyearResponses[keyof OpenCampyearResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8084' | (string & {});
};