// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateVolunteerData, CreateVolunteerErrors, CreateVolunteerResponses, DeleteVolunteerData, DeleteVolunteerErrors, DeleteVolunteerResponses, GetVolunteerByPersonData, GetVolunteerByPersonErrors, GetVolunteerByPersonResponses, GetVolunteerData, GetVolunteerErrors, GetVolunteerResponses, ListVolunteersData, ListVolunteersErrors, ListVolunteersResponses, UpdateAttendanceData, UpdateAttendanceErrors, UpdateAttendanceResponses, UpdateVolunteerData, UpdateVolunteerErrors, UpdateVolunteerResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create a new volunteer
 *
 * Create a new volunteer with the provided information
 */
export const createVolunteer = <ThrowOnError extends boolean = false>(options: Options<CreateVolunteerData, ThrowOnError>) => (options.client ?? client).post<CreateVolunteerResponses, CreateVolunteerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update a volunteers attendance
 *
 * Update a volunteer's attendance information by their ID
 */
export const updateAttendance = <ThrowOnError extends boolean = false>(options: Options<UpdateAttendanceData, ThrowOnError>) => (options.client ?? client).put<UpdateAttendanceResponses, UpdateAttendanceErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/attendance/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List volunteers by camp year
 *
 * Retrieve a list of volunteers filtered by camp year
 */
export const listVolunteers = <ThrowOnError extends boolean = false>(options: Options<ListVolunteersData, ThrowOnError>) => (options.client ?? client).get<ListVolunteersResponses, ListVolunteersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/list/{year}',
    ...options
});

/**
 * Get volunteers by person ID
 *
 * Retrieve all volunteers for a person by their person ID
 */
export const getVolunteerByPerson = <ThrowOnError extends boolean = false>(options: Options<GetVolunteerByPersonData, ThrowOnError>) => (options.client ?? client).get<GetVolunteerByPersonResponses, GetVolunteerByPersonErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/person/{id}',
    ...options
});

/**
 * Delete a volunteer
 *
 * Delete a volunteer by their ID
 */
export const deleteVolunteer = <ThrowOnError extends boolean = false>(options: Options<DeleteVolunteerData, ThrowOnError>) => (options.client ?? client).delete<DeleteVolunteerResponses, DeleteVolunteerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/{id}',
    ...options
});

/**
 * Get a volunteer by ID
 *
 * Retrieve a volunteer's details by their ID
 */
export const getVolunteer = <ThrowOnError extends boolean = false>(options: Options<GetVolunteerData, ThrowOnError>) => (options.client ?? client).get<GetVolunteerResponses, GetVolunteerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/{id}',
    ...options
});

/**
 * Update a volunteer
 *
 * Update a volunteer's information by their ID
 */
export const updateVolunteer = <ThrowOnError extends boolean = false>(options: Options<UpdateVolunteerData, ThrowOnError>) => (options.client ?? client).put<UpdateVolunteerResponses, UpdateVolunteerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
