// This file is auto-generated by @hey-api/openapi-ts

export type main_ApiError = {
    code: string;
    description: string;
    fields?: {
        [key: string]: (string);
    };
    message: string;
    meta?: {
        [key: string]: (string);
    };
};

export type main_RequestCreateUser = {
    email: string;
    nickname?: string;
    password?: string;
    user_metadata?: {
        [key: string]: unknown;
    };
};

export type main_ResponseUser = {
    email?: string;
    id?: string;
    nickname?: string;
    user_metadata?: {
        [key: string]: unknown;
    };
};

export type ListUsersData = {
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Users per page
         */
        per_page?: number;
    };
};

export type ListUsersResponse = (Array<main_ResponseUser>);

export type ListUsersError = ({
    [key: string]: (string);
});

export type CreateUserData = {
    /**
     * User to create
     */
    body: main_RequestCreateUser;
};

export type CreateUserResponse = (main_ResponseUser);

export type CreateUserError = ({
    [key: string]: (string);
} | main_ApiError);

export type GetUserData = {
    path: {
        /**
         * User ID
         */
        id: string;
    };
};

export type GetUserResponse = (main_ResponseUser);

export type GetUserError = ({
    [key: string]: (string);
});

export type UpdateUserData = {
    /**
     * User to update
     */
    body: main_RequestCreateUser;
    path: {
        /**
         * User ID
         */
        id: string;
    };
};

export type UpdateUserResponse = (main_ResponseUser);

export type UpdateUserError = ({
    [key: string]: (string);
});

export type DeleteUserData = {
    path: {
        /**
         * User ID
         */
        id: string;
    };
};

export type DeleteUserResponse = (void);

export type DeleteUserError = ({
    [key: string]: (string);
});