// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateRegistrationData, CreateRegistrationErrors, CreateRegistrationResponses, DeleteParticipantData, DeleteParticipantErrors, DeleteParticipantResponses, ExportParticipantsData, ExportParticipantsErrors, ExportParticipantsResponses, GetAllParticipantsData, GetAllParticipantsErrors, GetAllParticipantsResponses, GetParticipantData, GetParticipantErrors, GetParticipantResponses, UpdateParticipantData, UpdateParticipantErrors, UpdateParticipantResponses, UpdatePaymentData, UpdatePaymentErrors, UpdatePaymentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Export participants as CSV
 *
 * Exports all participants for the active camp year along with their latest payment details.
 */
export const exportParticipants = <ThrowOnError extends boolean = false>(options?: Options<ExportParticipantsData, ThrowOnError>) => (options?.client ?? client).get<ExportParticipantsResponses, ExportParticipantsErrors, ThrowOnError>({ url: '/export/api/v1/participants', ...options });

/**
 * Get all participants by active year
 *
 * Retrieves all participants for the active campyear.
 */
export const getAllParticipants = <ThrowOnError extends boolean = false>(options?: Options<GetAllParticipantsData, ThrowOnError>) => (options?.client ?? client).get<GetAllParticipantsResponses, GetAllParticipantsErrors, ThrowOnError>({ url: '/participant/api/v1/', ...options });

/**
 * Delete a participant
 *
 * Deletes a participant by its ID.
 */
export const deleteParticipant = <ThrowOnError extends boolean = false>(options: Options<DeleteParticipantData, ThrowOnError>) => (options.client ?? client).delete<DeleteParticipantResponses, DeleteParticipantErrors, ThrowOnError>({ url: '/participant/api/v1/{id}', ...options });

/**
 * Get a participant
 *
 * Retrieves a specific participant by its ID.
 */
export const getParticipant = <ThrowOnError extends boolean = false>(options: Options<GetParticipantData, ThrowOnError>) => (options.client ?? client).get<GetParticipantResponses, GetParticipantErrors, ThrowOnError>({ url: '/participant/api/v1/{id}', ...options });

/**
 * Update a participant
 *
 * Updates the details of a participant by its ID.
 */
export const updateParticipant = <ThrowOnError extends boolean = false>(options: Options<UpdateParticipantData, ThrowOnError>) => (options.client ?? client).put<UpdateParticipantResponses, UpdateParticipantErrors, ThrowOnError>({
    url: '/participant/api/v1/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update a specific payment
 *
 * Updates the details of a payment by its id.
 */
export const updatePayment = <ThrowOnError extends boolean = false>(options: Options<UpdatePaymentData, ThrowOnError>) => (options.client ?? client).put<UpdatePaymentResponses, UpdatePaymentErrors, ThrowOnError>({
    url: '/payment/api/v1/{year}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register for Haag Uit
 *
 * Creates a camp registration and redirects to payment if ideal.
 */
export const createRegistration = <ThrowOnError extends boolean = false>(options: Options<CreateRegistrationData, ThrowOnError>) => (options.client ?? client).post<CreateRegistrationResponses, CreateRegistrationErrors, ThrowOnError>({
    url: '/registration/api/v1/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
