// This file is auto-generated by @hey-api/openapi-ts

export type request_CampyearRequest = {
    end: string;
    insuranceFee?: number;
    participationFee: number;
    start: string;
    year: number;
};

export type request_RegistrationRequest = {
    accountCity?: string;
    accountName?: string;
    accountNumber?: string;
    address: string;
    city: string;
    comment?: string;
    dateOfBirth: string;
    email: string;
    emergencyContact: string;
    firstName: string;
    gender: 'm' | 'v' | 'nb';
    insurance?: boolean;
    lastName: string;
    paymentMethod: 'ideal' | 'incasso';
    phone: string;
    shirtSize: 'XS' | 'S' | 'M' | 'L' | 'XL';
    study: 'hbo-ict' | 'cmd' | 'ads-ai';
    termsConditions: boolean;
    zipCode: string;
};

export type request_UpdateCampyearRequest = {
    end?: string;
    insuranceFee?: number;
    participationFee?: number;
    start?: string;
};

export type request_UpdateParticipantRequest = {
    attendance?: 'open' | 'aanwezig' | 'afwezig' | 'afgemeld';
    shirt_size?: 'XS' | 'S' | 'M' | 'L' | 'XL';
};

export type request_UpdatePaymentRequest = {
    payment_status?: 'paid';
};

export type response_ApiError = {
    code: string;
    description: string;
    fields?: {
        [key: string]: (string);
    };
    message: string;
    meta?: {
        [key: string]: (string);
    };
};

export type response_CampyearResponse = {
    active?: boolean;
    end?: string;
    insuranceFee?: number;
    open?: boolean;
    participationFee?: number;
    start?: string;
    year?: number;
};

export type response_ParticipantResponse = {
    attendance: string;
    campyear_year: number;
    comment?: string;
    created_at: string;
    id: number;
    insurance: boolean;
    payments?: Array<response_PaymentResponse>;
    person: response_PersonResponse;
    shirt_size: string;
    study: string;
};

export type response_ParticipantWithLatestPaymentResponse = {
    attendance: string;
    campyear_year: number;
    comment?: string;
    created_at: string;
    id: number;
    insurance: boolean;
    latest_payment?: response_PaymentResponse;
    payments?: Array<response_PaymentResponse>;
    person: response_PersonResponse;
    shirt_size: string;
    study: string;
};

export type response_PaymentResponse = {
    account_city?: string;
    account_name?: string;
    account_number?: string;
    amount: number;
    created_at: string;
    id: number;
    payment_id: string;
    payment_method: string;
    payment_status: string;
};

export type response_PersonResponse = {
    address: string;
    city: string;
    date_of_birth: string;
    email: string;
    emergency_contact: string;
    first_name: string;
    gender: string;
    id: number;
    last_name: string;
    phone: string;
    zipcode: string;
};

export type GetAllCampyearsResponse = (Array<response_CampyearResponse>);

export type GetAllCampyearsError = (string);

export type CreateCampyearData = {
    /**
     * Campyear object to be created
     */
    body: request_CampyearRequest;
};

export type CreateCampyearResponse = (response_CampyearResponse);

export type CreateCampyearError = (response_ApiError);

export type GetCampyearData = {
    path: {
        /**
         * Year of the campyear
         */
        year: number;
    };
};

export type GetCampyearResponse = (response_CampyearResponse);

export type GetCampyearError = (response_ApiError);

export type UpdateCampyearData = {
    /**
     * Updated campyear object
     */
    body: request_UpdateCampyearRequest;
    path: {
        /**
         * Year of the campyear
         */
        year: number;
    };
};

export type UpdateCampyearResponse = (response_CampyearResponse);

export type UpdateCampyearError = (response_ApiError);

export type DeleteCampyearData = {
    path: {
        /**
         * Year of the campyear
         */
        year: number;
    };
};

export type DeleteCampyearResponse = (string);

export type DeleteCampyearError = (response_ApiError);

export type ActivateCampyearData = {
    path: {
        /**
         * Year of the campyear
         */
        year: number;
    };
};

export type ActivateCampyearResponse = (string);

export type ActivateCampyearError = (response_ApiError);

export type CloseCampyearData = {
    path: {
        /**
         * Year of the campyear
         */
        year: number;
    };
};

export type CloseCampyearResponse = (string);

export type CloseCampyearError = (response_ApiError);

export type OpenCampyearData = {
    path: {
        /**
         * Year of the campyear
         */
        year: number;
    };
};

export type OpenCampyearResponse = (string);

export type OpenCampyearError = (response_ApiError);

export type ExportParticipantsResponse = ((Blob | File));

export type ExportParticipantsError = (string);

export type GetAllParticipantsResponse = (Array<response_ParticipantWithLatestPaymentResponse>);

export type GetAllParticipantsError = (response_ApiError);

export type GetParticipantData = {
    path: {
        /**
         * ID of the participant
         */
        id: number;
    };
};

export type GetParticipantResponse = (response_ParticipantResponse);

export type GetParticipantError = (response_ApiError);

export type UpdateParticipantData = {
    /**
     * Updated participant object
     */
    body: request_UpdateParticipantRequest;
    path: {
        /**
         * ID of the participant
         */
        id: number;
    };
};

export type UpdateParticipantResponse = (response_ParticipantResponse);

export type UpdateParticipantError = (response_ApiError);

export type DeleteParticipantData = {
    path: {
        /**
         * ID of the participant
         */
        id: number;
    };
};

export type DeleteParticipantResponse = (string);

export type DeleteParticipantError = (response_ApiError);

export type UpdatePaymentData = {
    /**
     * Updated payment object
     */
    body: request_UpdatePaymentRequest;
    path: {
        /**
         * ID of the payment
         */
        id: number;
    };
};

export type UpdatePaymentResponse = (response_PaymentResponse);

export type UpdatePaymentError = (string);

export type CreateRegistrationData = {
    /**
     * Registration object to be created
     */
    body: request_RegistrationRequest;
};

export type CreateRegistrationResponse = (string);

export type CreateRegistrationError = (string);